//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "704a44f9a869e248")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1064 with alias "fADPage"
	/// <summary>FAD Page</summary>
	public partial interface IFAdpage : IPublishedContent
	{
		/// <summary>Footer Show</summary>
		bool FooterShow { get; }

		/// <summary>Footer Text</summary>
		string FooterText { get; }

		/// <summary>Menu Show</summary>
		bool MenuShow { get; }

		/// <summary>Menu Text</summary>
		string MenuText { get; }
	}

	/// <summary>FAD Page</summary>
	[PublishedContentModel("fADPage")]
	public partial class FAdpage : PublishedContentModel, IFAdpage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdpage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdpage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer Show
		///</summary>
		[ImplementPropertyType("footerShow")]
		public bool FooterShow
		{
			get { return GetFooterShow(this); }
		}

		/// <summary>Static getter for Footer Show</summary>
		public static bool GetFooterShow(IFAdpage that) { return that.GetPropertyValue<bool>("footerShow"); }

		///<summary>
		/// Footer Text
		///</summary>
		[ImplementPropertyType("footerText")]
		public string FooterText
		{
			get { return GetFooterText(this); }
		}

		/// <summary>Static getter for Footer Text</summary>
		public static string GetFooterText(IFAdpage that) { return that.GetPropertyValue<string>("footerText"); }

		///<summary>
		/// Menu Show
		///</summary>
		[ImplementPropertyType("menuShow")]
		public bool MenuShow
		{
			get { return GetMenuShow(this); }
		}

		/// <summary>Static getter for Menu Show</summary>
		public static bool GetMenuShow(IFAdpage that) { return that.GetPropertyValue<bool>("menuShow"); }

		///<summary>
		/// Menu Text
		///</summary>
		[ImplementPropertyType("menuText")]
		public string MenuText
		{
			get { return GetMenuText(this); }
		}

		/// <summary>Static getter for Menu Text</summary>
		public static string GetMenuText(IFAdpage that) { return that.GetPropertyValue<string>("menuText"); }
	}

	/// <summary>FAD Page - Home</summary>
	[PublishedContentModel("fADPageHome")]
	public partial class FAdpageHome : PublishedContentModel, IFAdpage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADPageHome";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdpageHome(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdpageHome, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About FAD
		///</summary>
		[ImplementPropertyType("aboutFAD")]
		public IHtmlString AboutFad
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutFAD"); }
		}

		///<summary>
		/// Food Images
		///</summary>
		[ImplementPropertyType("foodImages")]
		public IEnumerable<IPublishedContent> FoodImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("foodImages"); }
		}

		///<summary>
		/// Footer Show
		///</summary>
		[ImplementPropertyType("footerShow")]
		public bool FooterShow
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetFooterShow(this); }
		}

		///<summary>
		/// Footer Text
		///</summary>
		[ImplementPropertyType("footerText")]
		public string FooterText
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetFooterText(this); }
		}

		///<summary>
		/// Menu Show
		///</summary>
		[ImplementPropertyType("menuShow")]
		public bool MenuShow
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetMenuShow(this); }
		}

		///<summary>
		/// Menu Text
		///</summary>
		[ImplementPropertyType("menuText")]
		public string MenuText
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetMenuText(this); }
		}
	}

	/// <summary>FAD Page - About Us</summary>
	[PublishedContentModel("fADPageAboutUs")]
	public partial class FAdpageAboutUs : PublishedContentModel, IFAdpage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADPageAboutUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdpageAboutUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdpageAboutUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About Food And Drink
		///</summary>
		[ImplementPropertyType("aboutFoodAndDrink")]
		public IHtmlString AboutFoodAndDrink
		{
			get { return this.GetPropertyValue<IHtmlString>("aboutFoodAndDrink"); }
		}

		///<summary>
		/// Photo
		///</summary>
		[ImplementPropertyType("photo")]
		public IPublishedContent Photo
		{
			get { return this.GetPropertyValue<IPublishedContent>("photo"); }
		}

		///<summary>
		/// Footer Show
		///</summary>
		[ImplementPropertyType("footerShow")]
		public bool FooterShow
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetFooterShow(this); }
		}

		///<summary>
		/// Footer Text
		///</summary>
		[ImplementPropertyType("footerText")]
		public string FooterText
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetFooterText(this); }
		}

		///<summary>
		/// Menu Show
		///</summary>
		[ImplementPropertyType("menuShow")]
		public bool MenuShow
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetMenuShow(this); }
		}

		///<summary>
		/// Menu Text
		///</summary>
		[ImplementPropertyType("menuText")]
		public string MenuText
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetMenuText(this); }
		}
	}

	/// <summary>FAD Site</summary>
	[PublishedContentModel("fADSite")]
	public partial class FAdsite : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADSite";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdsite(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdsite, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Site Description
		///</summary>
		[ImplementPropertyType("siteDescription")]
		public string SiteDescription
		{
			get { return this.GetPropertyValue<string>("siteDescription"); }
		}

		///<summary>
		/// Site Logo
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public IPublishedContent SiteLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("siteLogo"); }
		}

		///<summary>
		/// Site Logo Footer
		///</summary>
		[ImplementPropertyType("siteLogoFooter")]
		public IPublishedContent SiteLogoFooter
		{
			get { return this.GetPropertyValue<IPublishedContent>("siteLogoFooter"); }
		}

		///<summary>
		/// Site Title
		///</summary>
		[ImplementPropertyType("siteTitle")]
		public string SiteTitle
		{
			get { return this.GetPropertyValue<string>("siteTitle"); }
		}
	}

	/// <summary>FAD Home Highlight Food</summary>
	[PublishedContentModel("fADHomeHighlightFood")]
	public partial class FAdhomeHighlightFood : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADHomeHighlightFood";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdhomeHighlightFood(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdhomeHighlightFood, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Food Image
		///</summary>
		[ImplementPropertyType("foodImage")]
		public IPublishedContent FoodImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("foodImage"); }
		}

		///<summary>
		/// Price
		///</summary>
		[ImplementPropertyType("price")]
		public int Price
		{
			get { return this.GetPropertyValue<int>("price"); }
		}
	}

	/// <summary>FAD About Chef</summary>
	[PublishedContentModel("fADAboutChef")]
	public partial class FAdaboutChef : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADAboutChef";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdaboutChef(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdaboutChef, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Display Name
		///</summary>
		[ImplementPropertyType("displayName")]
		public string DisplayName
		{
			get { return this.GetPropertyValue<string>("displayName"); }
		}

		///<summary>
		/// Person Summary
		///</summary>
		[ImplementPropertyType("personSummary")]
		public IHtmlString PersonSummary
		{
			get { return this.GetPropertyValue<IHtmlString>("personSummary"); }
		}

		///<summary>
		/// Photo
		///</summary>
		[ImplementPropertyType("photo")]
		public IPublishedContent Photo
		{
			get { return this.GetPropertyValue<IPublishedContent>("photo"); }
		}
	}

	/// <summary>FAD Page - Menu</summary>
	[PublishedContentModel("fADPageMenu")]
	public partial class FAdpageMenu : PublishedContentModel, IFAdfolderGenerator, IFAdpage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADPageMenu";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdpageMenu(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdpageMenu, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Folder Type Alias
		///</summary>
		[ImplementPropertyType("folderTypeAlias")]
		public string FolderTypeAlias
		{
			get { return Umbraco.Web.PublishedContentModels.FAdfolderGenerator.GetFolderTypeAlias(this); }
		}

		///<summary>
		/// Generate Folder
		///</summary>
		[ImplementPropertyType("generateFolder")]
		public bool GenerateFolder
		{
			get { return Umbraco.Web.PublishedContentModels.FAdfolderGenerator.GetGenerateFolder(this); }
		}

		///<summary>
		/// Footer Show
		///</summary>
		[ImplementPropertyType("footerShow")]
		public bool FooterShow
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetFooterShow(this); }
		}

		///<summary>
		/// Footer Text
		///</summary>
		[ImplementPropertyType("footerText")]
		public string FooterText
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetFooterText(this); }
		}

		///<summary>
		/// Menu Show
		///</summary>
		[ImplementPropertyType("menuShow")]
		public bool MenuShow
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetMenuShow(this); }
		}

		///<summary>
		/// Menu Text
		///</summary>
		[ImplementPropertyType("menuText")]
		public string MenuText
		{
			get { return Umbraco.Web.PublishedContentModels.FAdpage.GetMenuText(this); }
		}
	}

	/// <summary>FAD Menu Folder</summary>
	[PublishedContentModel("fADMenuFolder")]
	public partial class FAdmenuFolder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADMenuFolder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdmenuFolder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdmenuFolder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>FAD Menu Food</summary>
	[PublishedContentModel("fADMenuFood")]
	public partial class FAdmenuFood : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADMenuFood";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdmenuFood(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdmenuFood, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description: Enter the receipt, ingredient of food
		///</summary>
		[ImplementPropertyType("description")]
		public IHtmlString Description
		{
			get { return this.GetPropertyValue<IHtmlString>("description"); }
		}

		///<summary>
		/// Display Name
		///</summary>
		[ImplementPropertyType("displayName")]
		public string DisplayName
		{
			get { return this.GetPropertyValue<string>("displayName"); }
		}

		///<summary>
		/// From Date
		///</summary>
		[ImplementPropertyType("fromDate")]
		public DateTime FromDate
		{
			get { return this.GetPropertyValue<DateTime>("fromDate"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Price
		///</summary>
		[ImplementPropertyType("price")]
		public int Price
		{
			get { return this.GetPropertyValue<int>("price"); }
		}

		///<summary>
		/// To Date
		///</summary>
		[ImplementPropertyType("toDate")]
		public DateTime ToDate
		{
			get { return this.GetPropertyValue<DateTime>("toDate"); }
		}
	}

	/// <summary>FAD Page - Order List</summary>
	[PublishedContentModel("fADPageOrderList")]
	public partial class FAdpageOrderList : PublishedContentModel, IFAdfolderGenerator
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADPageOrderList";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdpageOrderList(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdpageOrderList, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Folder Type Alias
		///</summary>
		[ImplementPropertyType("folderTypeAlias")]
		public string FolderTypeAlias
		{
			get { return Umbraco.Web.PublishedContentModels.FAdfolderGenerator.GetFolderTypeAlias(this); }
		}

		///<summary>
		/// Generate Folder
		///</summary>
		[ImplementPropertyType("generateFolder")]
		public bool GenerateFolder
		{
			get { return Umbraco.Web.PublishedContentModels.FAdfolderGenerator.GetGenerateFolder(this); }
		}
	}

	/// <summary>FAD Order List Folder</summary>
	[PublishedContentModel("fADOrderListFolder")]
	public partial class FAdorderListFolder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADOrderListFolder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdorderListFolder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdorderListFolder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>FAD Order Entry</summary>
	[PublishedContentModel("fADOrderEntry")]
	public partial class FAdorderEntry : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADOrderEntry";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdorderEntry(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdorderEntry, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("address"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// FullName
		///</summary>
		[ImplementPropertyType("fullName")]
		public string FullName
		{
			get { return this.GetPropertyValue<string>("fullName"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public string Phone
		{
			get { return this.GetPropertyValue<string>("phone"); }
		}

		///<summary>
		/// Submitted Datetime
		///</summary>
		[ImplementPropertyType("submittedDatetime")]
		public DateTime SubmittedDatetime
		{
			get { return this.GetPropertyValue<DateTime>("submittedDatetime"); }
		}
	}

	// Mixin content Type 1134 with alias "fADFolderGenerator"
	/// <summary>FAD Folder Generator</summary>
	public partial interface IFAdfolderGenerator : IPublishedContent
	{
		/// <summary>Folder Type Alias</summary>
		string FolderTypeAlias { get; }

		/// <summary>Generate Folder</summary>
		bool GenerateFolder { get; }
	}

	/// <summary>FAD Folder Generator</summary>
	[PublishedContentModel("fADFolderGenerator")]
	public partial class FAdfolderGenerator : PublishedContentModel, IFAdfolderGenerator
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADFolderGenerator";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdfolderGenerator(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdfolderGenerator, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Folder Type Alias
		///</summary>
		[ImplementPropertyType("folderTypeAlias")]
		public string FolderTypeAlias
		{
			get { return GetFolderTypeAlias(this); }
		}

		/// <summary>Static getter for Folder Type Alias</summary>
		public static string GetFolderTypeAlias(IFAdfolderGenerator that) { return that.GetPropertyValue<string>("folderTypeAlias"); }

		///<summary>
		/// Generate Folder
		///</summary>
		[ImplementPropertyType("generateFolder")]
		public bool GenerateFolder
		{
			get { return GetGenerateFolder(this); }
		}

		/// <summary>Static getter for Generate Folder</summary>
		public static bool GetGenerateFolder(IFAdfolderGenerator that) { return that.GetPropertyValue<bool>("generateFolder"); }
	}

	/// <summary>FAD Order Detail Entry</summary>
	[PublishedContentModel("fADOrderDetailEntry")]
	public partial class FAdorderDetailEntry : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fADOrderDetailEntry";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FAdorderDetailEntry(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FAdorderDetailEntry, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Amount
		///</summary>
		[ImplementPropertyType("amount")]
		public int Amount
		{
			get { return this.GetPropertyValue<int>("amount"); }
		}

		///<summary>
		/// Food Description
		///</summary>
		[ImplementPropertyType("foodDescription")]
		public IHtmlString FoodDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("foodDescription"); }
		}

		///<summary>
		/// Food Id
		///</summary>
		[ImplementPropertyType("foodId")]
		public int FoodId
		{
			get { return this.GetPropertyValue<int>("foodId"); }
		}

		///<summary>
		/// Food Name
		///</summary>
		[ImplementPropertyType("foodName")]
		public string FoodName
		{
			get { return this.GetPropertyValue<string>("foodName"); }
		}

		///<summary>
		/// Price
		///</summary>
		[ImplementPropertyType("price")]
		public int Price
		{
			get { return this.GetPropertyValue<int>("price"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
